name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Test
        uses: hieupth/docker-action@v1
        with: 
          image: perl
          run: |
            perl -E 'say "Is STDOUT a TTY?: ", -t STDOUT ? "yes" : "no"'
            docker ps -a
