name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Run
        uses: hieupth/docker-action@v3
        with: 
          image: perl
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          run: |
            perl -E 'say "Is STDOUT a TTY?: ", -t STDOUT ? "yes" : "no"'
            docker ps -a
      -
        name: Push image
        run: |
          docker tag perl ${{secrets.DOCKERHUB_USERNAME}}/docker-action-test
          docker push ${{secrets.DOCKERHUB_USERNAME}}/docker-action-test
