name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Test
        uses: hieupth/docker-action@v1
        with: 
          image: nvcr.io/nvidia/tensorrt:24.08-py3
